//Collections
LIST => {0=>'Yavuz', 1=>'Ali', 2=>'Sri', 3=>'Emir', 4=>'AY', 5=>'Ali'}
1. Insertion order is preserved
2. Allows duplicate values

SET => {'Bala', 'Yavuz', 'Mustafa'}
1. Insertion order is not preserved
2. Doesnt allow duplicates. If you try to store duplicates, it skips them

MAP => {(key='Bala', value=''), (key='', value=''), (key='', value='')}
1. Key & Value combintion
2. Key are unique
3. Values can be duplicate
